const API_BASE_URL = process.env.REACT_APP_API_URL || "http://localhost:5000/api";
const WHATSAPP_ASSISTANT_URL = process.env.REACT_APP_WHATSAPP_URL || "http://localhost:5001";

const WHATSAPP_NUMBER = "+14155238886";
const WHATSAPP_SANDBOX_MESSAGE = "join ill-stretch";

export { API_BASE_URL, WHATSAPP_ASSISTANT_URL, WHATSAPP_NUMBER, WHATSAPP_SANDBOX_MESSAGE };
